image: tmaier/docker-compose:latest

variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  - deploy
  - update_seeds

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose --version

build:
  stage: build
  tags:
    - docker
  script:
    - docker-compose build

deploy:
  stage: deploy
  tags:
    - docker
  script:
    - docker-compose run app rake db:create db:migrate RAILS_ENV=production
    - docker-compose up -d
    - docker ps

replant_seeds:
  stage: update_seeds
  tags:
    - docker
  script:
    - docker-compose run app rake db:seed:replant RAILS_ENV=production DISABLE_DATABASE_ENVIRONMENT_CHECK=1
  when: manual
