version: '2'

services:
  app:
    volumes:
      - rrdb-sync:/application:nocopy # nocopy is important
  webpack:
    volumes:
      - rrdb-sync:/application:nocopy # nocopy is important

volumes:
  rrdb-sync:
    external: true
