# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db

development:
  <<: *default
  database: xop_landing_page_development
  username: postgres
  password: xoplv
  host: localhost
  port: 5432

test:
  <<: *default
  database: xop_landing_page_test

production:
  <<: *default
  database: xop_landing_page_production
  username: postgres
  host: db
  password: <%= ENV['XOP_LANDING_PAGE_DATABASE_PASSWORD'] %>
